name: Android CI

on:
  push:
    branches: [ "Mi8937" ]
  pull_request:
    branches: [ "Mi8937" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Send start notification to Telegram
      run: |
        COMMIT_ID="${{ github.sha }}"
        SHORT_COMMIT_ID="${COMMIT_ID:0:7}"
        COMMIT_URL="https://github.com/${{ github.repository }}/commit/$COMMIT_ID"
        MESSAGE="Honey, start test build RvKernel Manager using GitHub Action%0A%0ATriggered by <a href=\"$COMMIT_URL\">$SHORT_COMMIT_ID</a>"
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="$MESSAGE" \
        -d parse_mode="HTML" \
        -d disable_web_page_preview="true"

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk

    - name: Send success notification to Telegram
      if: success()
      run: |
        COMMIT_ID="${{ github.sha }}"
        SHORT_COMMIT_ID="${COMMIT_ID:0:7}"
        COMMIT_URL="https://github.com/${{ github.repository }}/commit/$COMMIT_ID"
        MESSAGE="Honey, test build RvKernel Manager completed successfully%0A%0ALast commit: <a href=\"$COMMIT_URL\">$SHORT_COMMIT_ID</a>"
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="$MESSAGE" \
        -d parse_mode="HTML" \
        -d disable_web_page_preview="true"

    - name: Send failure notification to Telegram
      if: failure()
      run: |
        COMMIT_ID="${{ github.sha }}"
        SHORT_COMMIT_ID="${COMMIT_ID:0:7}"
        COMMIT_URL="https://github.com/${{ github.repository }}/commit/$COMMIT_ID"
        MESSAGE="Honey, test build RvKernel Manager failed%0A%0ALast commit: <a href=\"$COMMIT_URL\">$SHORT_COMMIT_ID</a>"
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="$MESSAGE" \
        -d parse_mode="HTML" \
        -d disable_web_page_preview="true"
