name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    path:
      - 'rvkernel-manager/**'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rvkernel-manager

    steps:
    - uses: actions/checkout@v4

    - name: Write keystore
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        echo "storeFile=$GITHUB_WORKSPACE/key.jks" >> keystore.properties
        echo "${{ secrets.KEYSTORE }}" | base64 -d > $GITHUB_WORKSPACE/key.jks

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean assembleRelease

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: RvKernel-Manager
        path: rvkernel-manager/app/build/outputs/apk/release/*.apk
