name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Send start notification to Telegram
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="Honey, start test build RvKernel Manager using GitHub Action"
        
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Send success notification to Telegram
      if: success()
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="Honey, Test build RvKernel Manager completed successfully <3"
        
    - name: Send failure notification to Telegram
      if: failure()
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage" \
        -d chat_id="${{ secrets.TG_CHAT_ID }}" \
        -d text="Honey, test build RvKernel Manager failed :("